name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    name: Build and Test (SwiftPM)
    runs-on: macos-14
    strategy:
      matrix:
        aa_mode: [eip7702, default]
    env:
      AA_MODE: ${{ matrix.aa_mode }}
      AA_TEST_PRIVKEY: ${{ secrets.AA_TEST_PRIVKEY }}
      AA_TEST_ALCHEMY_API_KEY: ${{ secrets.AA_TEST_ALCHEMY_API_KEY }}
      AA_TEST_ALCHEMY_GAS_POLICY_ID: ${{ secrets.AA_TEST_ALCHEMY_GAS_POLICY_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Show Swift version
        run: swift --version

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build
        run: swift build --configuration debug

      - name: Run tests
        run: swift test --parallel --enable-code-coverage --verbose